import { useState, useEffect, useRef } from 'react';

const LEFT_SOURCES = [
  { id: 'src0', title: 'SAP Applications', sublabel: 'Ariba, SuccessFactors, Concur & more', icon: '🏢', iconClass: 'icon-sap', tip: 'SAP Applications|Connect any SAP application — Ariba, SuccessFactors, Concur, BW, and more.', color: '#3dd68c', speed: 'fast' },
  { id: 'src1', title: 'SAP S/4HANA', sublabel: 'ERP financials & materials', icon: '⚙️', iconClass: 'icon-sap', tip: 'SAP S/4HANA|Financial ledgers, cost centers, and material master data.', color: '#3dd68c', speed: '' },
  { id: 'src2', title: 'Non-SAP ERP', sublabel: 'Any ERP system', icon: '🔗', iconClass: 'icon-erp', tip: 'Non-SAP ERP|Connect any non-SAP ERP system via file exports or API integrations.', color: '#4f8eff', speed: 'mid' },
  { id: 'src3', title: 'Excel / XLSX', sublabel: 'With optional schema sheet', icon: '📊', iconClass: 'icon-excel', tip: 'Excel / XLSX|Upload .xlsx with optional schema Sheet2 — DataGenie auto-detects types.', color: '#f5c542', speed: 'slow' },
  { id: 'src4', title: 'CSV Files', sublabel: 'Auto-typed, instant preview', icon: '📄', iconClass: 'icon-csv', tip: 'CSV Files|Drag-and-drop any CSV, auto-typed and loaded into the SQL engine.', color: '#f5c542', speed: 'fast' },
  { id: 'src5', title: 'SQL Databases', sublabel: 'Postgres, MySQL, SQLite', icon: '🗄️', iconClass: 'icon-db', tip: 'SQL Database|Connect to Postgres, MySQL, or SQLite — tables auto-introspected.', color: '#4f8eff', speed: 'mid' },
  { id: 'src6', title: 'REST APIs', sublabel: 'JSON → tabular transform', icon: '🌐', iconClass: 'icon-api', tip: 'REST APIs|Fetch JSON endpoints and normalize to tabular data.', color: '#3dd68c', speed: 'slow' }
];

const OUTPUT_CARDS = [
  { id: 'out0', title: 'Dataset Preview', desc: 'First 50 rows with column types, table name, row/col counts.', color: '#f5c542', speed: 'fast' },
  { id: 'out1', title: 'Schema Explorer', desc: 'Sanitized column list with dtypes, descriptions, and name mapping.', color: '#4f8eff', speed: 'mid' },
  { id: 'out2', title: 'SQL Query Answer', desc: 'Natural-language question → generated SQL → executed result table.', color: '#3dd68c', speed: 'slow' },
  { id: 'out3', title: 'Auto Chart', desc: 'Best-fit Plotly chart from the SQL result set.', color: '#b47aff', speed: 'fast' },
  { id: 'out4', title: 'Insight Summary', desc: 'Plain-English 2–3 sentence takeaway generated by LLM.', color: '#f5c542', speed: 'mid' },
  { id: 'out5', title: 'Auto-Insights Report', desc: 'LLM hypotheses → SQL → summaries for top 5–12 questions.', color: '#ff6b6b', speed: 'slow' },
  { id: 'out6', title: 'Conversational Q&A', desc: 'Multi-turn chat with session history and follow-ups.', color: '#3dd68c', speed: 'fast' },
  { id: 'out7', title: 'Suggested Questions', desc: 'Schema-aware questions to explore the dataset further.', color: '#4f8eff', speed: 'mid' }
];

const AGENTS_TOP = [
  { name: 'Schema\nProfiler', icon: '🧩', desc: 'Types, nulls & column context', styleClass: 'accent-blue', tip: 'Schema Agent|Sanitizes column names, infers data types, builds a rich data dictionary.' },
  { name: 'SQL\nGenerator', icon: '🔍', desc: 'NL → SQL via LLM', styleClass: 'accent-green', tip: 'SQL Agent|Translates natural-language questions into optimized SQL using the data dictionary.' },
  { name: 'Hypothesis\nEngine', icon: '💡', desc: 'Auto-suggest questions', styleClass: 'accent-yel', tip: 'Hypothesis Agent|Uses GPT to propose high-value analytical questions from your columns.' }
];

const AGENTS_BOTTOM = [
  { name: 'Session\nManager', icon: '💬', desc: 'Multi-turn chat history', styleClass: 'accent-blue', tip: 'Session Agent|Manages multi-turn chat sessions per dataset with full Q&A history.' },
  { name: 'Guardrails\nAgent', icon: '🛡️', desc: 'Policy-aware responses', styleClass: 'accent-green', tip: 'Fixed QA Agent|Intercepts known questions and returns canned answers instantly.' },
  { name: 'Data\nSanitizer', icon: '🔒', desc: 'Identifier safety layer', styleClass: 'accent-yel', tip: 'Sanitizer|Strips unsafe SQL characters from column and table names.' }
];

const CAPABILITIES = [
  { name: 'Dataset\nMemory', icon: '🧠', desc: 'Schema & session context', tip: 'Data Memory|Dataset stored in-memory with full metadata: type, table name, schema, raw bytes.' },
  { name: 'NL→SQL\nSkills', icon: '⚡', desc: 'LLM query generation', tip: 'NL-to-SQL|GPT-4o with data dictionary, column descriptions, and chat history as context.' },
  { name: 'Data\nGuardrails', icon: '🛡️', desc: 'Grounded & safe responses', tip: 'Guardrails|Fixed-answer intercepts, identifier sanitization, policy-aware response filters.' }
];

const IDLE_STATUSES = [
  'Engine ready · awaiting dataset',
  'LLM provider: OpenAI GPT-4o · connected',
  'Schema sanitizer · active',
  'In-memory SQL engine · standby',
  'Session store · 0 active sessions',
  'Auto-Insights · hypothesis mode ready'
];

export default function DataGeniePipeline() {
  const [statusText, setStatusText] = useState('LLM provider: OpenAI GPT-4o · connected');
  const [tooltip, setTooltip] = useState({ show: false, title: '', desc: '', x: 0, y: 0 });

  const layoutOuterRef = useRef(null);
  const arrowSvgRef = useRef(null);
  const engineBoxRef = useRef(null);
  const aiCoreRef = useRef(null);
  const elementsRef = useRef({});

  const drawArrows = () => {
    const svg = arrowSvgRef.current;
    const outer = layoutOuterRef.current;
    const engine = engineBoxRef.current;
    if (!svg || !outer || !engine) return;

    svg.innerHTML = '';
    const outerH = outer.getBoundingClientRect().height;
    const outerW = outer.getBoundingClientRect().width;
    svg.setAttribute('viewBox', `0 0 ${outerW} ${outerH}`);

    const midY = (el) => el.getBoundingClientRect().top - outer.getBoundingClientRect().top + el.getBoundingClientRect().height / 2;
    const rightX = (el) => el.getBoundingClientRect().right - outer.getBoundingClientRect().left;
    const leftX = (el) => el.getBoundingClientRect().left - outer.getBoundingClientRect().left;

    const engLeft = leftX(engine);
    const engRight = rightX(engine);
    const engTop = engine.getBoundingClientRect().top - outer.getBoundingClientRect().top;
    const engH = engine.getBoundingClientRect().height;
    const engMidY = engTop + engH / 2;

    const entrySpread = engH * 0.5;
    const entryStart = engMidY - entrySpread / 2;

    // Route Input Channels
    LEFT_SOURCES.forEach((src, i) => {
      const el = elementsRef.current[src.id];
      if (!el) return;
      const sx = rightX(el);
      const sy = midY(el);
      const ex = engLeft;
      const ey = entryStart + (i / (LEFT_SOURCES.length - 1)) * entrySpread;

      const cp1x = sx + (ex - sx) * 0.45;
      const cp2x = sx + (ex - sx) * 0.65;
      const d = `M ${sx} ${sy} C ${cp1x} ${sy}, ${cp2x} ${ey}, ${ex} ${ey}`;

      const glow = document.createElementNS('http://www.w3.org/2000/svg', 'path');
      glow.setAttribute('d', d);
      glow.setAttribute('class', 'glow-path');
      glow.setAttribute('stroke', src.color);
      svg.appendChild(glow);

      const path = document.createElementNS('http://www.w3.org/2000/svg', 'path');
      path.setAttribute('d', d);
      path.setAttribute('class', `flow-path ${src.speed}`);
      path.setAttribute('stroke', src.color);
      path.style.animationDelay = `${i * 0.3}s`;
      svg.appendChild(path);
    });

    // Route Output Channels
    OUTPUT_CARDS.forEach((card, i) => {
      const el = elementsRef.current[card.id];
      if (!el) return;
      const ex2 = leftX(el);
      const ey2 = midY(el);
      const sy2 = entryStart + (i / (OUTPUT_CARDS.length - 1)) * entrySpread;

      const cp1x = engRight + (ex2 - engRight) * 0.35;
      const cp2x = engRight + (ex2 - engRight) * 0.6;
      const d = `M ${engRight} ${sy2} C ${cp1x} ${sy2}, ${cp2x} ${ey2}, ${ex2} ${ey2}`;

      const glow = document.createElementNS('http://www.w3.org/2000/svg', 'path');
      glow.setAttribute('d', d);
      glow.setAttribute('class', 'glow-path');
      glow.setAttribute('stroke', card.color);
      svg.appendChild(glow);

      const path = document.createElementNS('http://www.w3.org/2000/svg', 'path');
      path.setAttribute('d', d);
      path.setAttribute('class', `flow-path ${i % 3 === 0 ? 'fast' : i % 3 === 1 ? 'mid' : 'slow'}`);
      path.setAttribute('stroke', card.color);
      path.style.animationDelay = `${i * 0.28}s`;
      svg.appendChild(path);
    });
  };

  useEffect(() => {
    const loadTimeout = setTimeout(drawArrows, 120);
    window.addEventListener('resize', drawArrows);

    // Dynamic configuration ticker cycles
    let idleIdx = 0;
    const statusInterval = setInterval(() => {
      setStatusText((current) => {
        const triggers = ['loaded', 'Ingesting', 'invoked', 'activated'];
        if (triggers.some(t => current.includes(t))) return current;
        idleIdx = (idleIdx + 1) % IDLE_STATUSES.length;
        return IDLE_STATUSES[idleIdx];
      });
    }, 3500);

    return () => {
      clearTimeout(loadTimeout);
      clearInterval(statusInterval);
      window.removeEventListener('resize', drawArrows);
    };
  }, []);

  // Structural Mouse Canvas Hover Trackers
  const handleMouseEnter = (e, tipString) => {
    const [title, desc] = tipString.split('|');
    setTooltip(prev => ({ ...prev, show: true, title, desc }));
    handleMouseMove(e);
  };

  const handleMouseMove = (e) => {
    const x = e.clientX + 14;
    const y = e.clientY - 10;
    const tw = 240; 
    const th = 80;  
    
    const adjustedX = x + tw > window.innerWidth ? x - tw - 28 : x;
    const adjustedY = y + th > window.innerHeight ? y - th - 10 : y;
    
    setTooltip(prev => ({ ...prev, x: adjustedX, y: adjustedY }));
  };

  const handleMouseLeave = () => {
    setTooltip(prev => ({ ...prev, show: false }));
  };

  // Node Element Click Trigger Pipelines
  const flashElement = (elId) => {
    const el = elementsRef.current[elId];
    if (!el) return;
    el.classList.add('flash');
    setTimeout(() => el.classList.remove('flash'), 700);
  };

  const handleAgentClick = (id, name) => {
    flashElement(id);
    setStatusText(`Agent activated: ${name.replace('\n', ' ')}`);
  };

  const handleCoreClick = () => {
    const core = aiCoreRef.current;
    if (!core) return;
    core.style.borderColor = 'var(--accent2)';
    core.style.boxShadow = '0 0 24px rgba(245,197,66,0.3)';
    setTimeout(() => {
      core.style.borderColor = '';
      core.style.boxShadow = '';
    }, 800);
    setStatusText('Core LLM invoked · generating SQL + insight');
  };

  const handleSourceClick = (id, name) => {
    flashElement(id);
    setStatusText(`Ingesting ${name} · profiling schema`);
    setTimeout(() => handleCoreClick(), 400);
    setTimeout(() => setStatusText(`${name} loaded · ready for questions`), 1400);
  };

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=JetBrains+Mono&display=swap');

        .dgenie-pipeline-wrapper {
          --bg: #0a0e1a;
          --surface: #0f1629;
          --surface2: #141c35;
          --border: rgba(99,160,255,0.12);
          --border-bright: rgba(99,160,255,0.3);
          --accent: #4f8eff;
          --accent2: #f5c542;
          --accent3: #3dd68c;
          --accent4: #ff6b6b;
          --accent5: #b47aff;
          --text: #e8eaf0;
          --text-muted: #7a86a8;
          --text-dim: #4a5370;

          background: var(--bg);
          color: var(--text);
          min-height: 100vh;
          font-family: 'Space Grotesk', sans-serif;
          position: relative;
          box-sizing: border-box;
        }

        .dgenie-pipeline-wrapper *, 
        .dgenie-pipeline-wrapper *::before, 
        .dgenie-pipeline-wrapper *::after { 
          box-sizing: border-box; 
          margin: 0; 
          padding: 0; 
        }

        .dgenie-pipeline-wrapper::before {
          content: '';
          position: fixed; inset: 0;
          background-image:
            linear-gradient(rgba(79,142,255,0.03) 1px, transparent 1px),
            linear-gradient(90deg, rgba(79,142,255,0.03) 1px, transparent 1px);
          background-size: 40px 40px;
          pointer-events: none;
          z-index: 0;
        }

        .dgenie-pipeline-wrapper .page {
          max-width: 1400px;
          margin: 0 auto;
          padding: 48px 32px 80px;
          position: relative;
          z-index: 1;
        }

        .dgenie-pipeline-wrapper .header { text-align: center; margin-bottom: 56px; }
        .dgenie-pipeline-wrapper .header h1 { font-size: clamp(28px,4vw,48px); font-weight: 700; letter-spacing: -0.5px; line-height: 1.1; }
        .dgenie-pipeline-wrapper .header h1 span { color: var(--accent2); }
        .dgenie-pipeline-wrapper .header p { margin-top: 12px; color: var(--text-muted); font-size: 15px; }

        .dgenie-pipeline-wrapper .layout-outer { position: relative; }
        .dgenie-pipeline-wrapper .layout { display: grid; grid-template-columns: 240px 1fr 280px; gap: 0; align-items: start; }

        .dgenie-pipeline-wrapper #arrow-svg { position: absolute; top: 0; left: 0; width: 100%; height: 100%; pointer-events: none; overflow: visible; z-index: 0; }
        .dgenie-pipeline-wrapper .left-col, .dgenie-pipeline-wrapper .right-col, .dgenie-pipeline-wrapper .center-col { position: relative; z-index: 1; }
        .dgenie-pipeline-wrapper .left-col { padding-right: 32px; }
        .dgenie-pipeline-wrapper .right-col { padding-left: 32px; }
        .dgenie-pipeline-wrapper .center-col { padding: 0 8px; }

        .dgenie-pipeline-wrapper .panel-title { font-size: 10px; font-weight: 600; letter-spacing: 2px; text-transform: uppercase; color: var(--text-dim); margin-bottom: 16px; padding-left: 4px; }
        .dgenie-pipeline-wrapper .source-group { margin-bottom: 24px; }
        .dgenie-pipeline-wrapper .source-group .group-label { font-size: 9px; font-weight: 600; letter-spacing: 2px; text-transform: uppercase; color: var(--text-dim); margin-bottom: 10px; padding-left: 4px; }
        
        .dgenie-pipeline-wrapper .source-item {
          display: flex; align-items: center; gap: 10px; padding: 10px 14px; background: var(--surface); border: 0.5px solid var(--border); border-radius: 10px; margin-bottom: 8px; cursor: pointer; transition: border-color 0.2s, background 0.2s;
        }
        .dgenie-pipeline-wrapper .source-item:hover, 
        .dgenie-pipeline-wrapper .source-item.active { border-color: var(--border-bright); background: var(--surface2); }
        .dgenie-pipeline-wrapper .source-item .icon { width: 32px; height: 32px; border-radius: 7px; display: flex; align-items: center; justify-content: center; font-size: 14px; flex-shrink: 0; }
        
        .dgenie-pipeline-wrapper .icon-sap { background: rgba(0,112,240,0.18); }
        .dgenie-pipeline-wrapper .icon-erp { background: rgba(61,214,140,0.15); }
        .dgenie-pipeline-wrapper .icon-excel { background: rgba(30,180,90,0.18); }
        .dgenie-pipeline-wrapper .icon-csv { background: rgba(245,197,66,0.15); }
        .dgenie-pipeline-wrapper .icon-db { background: rgba(180,122,255,0.15); }
        .dgenie-pipeline-wrapper .icon-api { background: rgba(255,107,107,0.15); }
        
        .dgenie-pipeline-wrapper .source-item .label { font-size: 13px; font-weight: 500; color: var(--text); }
        .dgenie-pipeline-wrapper .source-item .sublabel { font-size: 11px; color: var(--text-muted); margin-top: 1px; }
        .dgenie-pipeline-wrapper .dot { width:6px;height:6px;border-radius:50%;background:var(--accent3);margin-left:auto;flex-shrink:0;box-shadow:0 0 6px var(--accent3); }
        .dgenie-pipeline-wrapper .dot-yellow { background:var(--accent2);box-shadow:0 0 6px var(--accent2); }
        .dgenie-pipeline-wrapper .dot-blue { background:var(--accent); box-shadow:0 0 6px var(--accent); }

        .dgenie-pipeline-wrapper .center-col { display: flex; flex-direction: column; align-items: center; }
        .dgenie-pipeline-wrapper .engine-wrapper { background: var(--surface); border: 0.5px solid var(--border-bright); border-radius: 20px; padding: 28px 24px; width: 100%; position: relative; overflow: hidden; }
        .dgenie-pipeline-wrapper .engine-wrapper::before { content:''; position:absolute; top:-60px; left:50%; transform:translateX(-50%); width:300px; height:200px; background:radial-gradient(ellipse,rgba(79,142,255,0.08) 0%,transparent 70%); pointer-events:none; }
        .dgenie-pipeline-wrapper .engine-label { text-align:center; margin-bottom:20px; }
        .dgenie-pipeline-wrapper .engine-badge { display:inline-block; background:rgba(79,142,255,0.12); border:0.5px solid rgba(79,142,255,0.35); border-radius:999px; padding:5px 18px; font-size:12px; font-weight:600; letter-spacing:1px; color:var(--accent); text-transform:uppercase; margin-bottom:8px; }
        .dgenie-pipeline-wrapper .engine-subtitle { font-size:12px; color:var(--text-muted); }
        .dgenie-pipeline-wrapper .crew-label { font-size:9px; font-weight:600; letter-spacing:2px; text-transform:uppercase; color:var(--text-dim); text-align:center; margin-bottom:12px; }
        
        .dgenie-pipeline-wrapper .agents-top { display:flex; gap:10px; justify-content:center; margin-bottom:16px; }
        .dgenie-pipeline-wrapper .ai-core-row { display:flex; gap:10px; justify-content:center; align-items:center; margin-bottom:16px; }
        .dgenie-pipeline-wrapper .agents-bottom { display:flex; gap:10px; justify-content:center; }
        
        .dgenie-pipeline-wrapper .agent-card { background:var(--surface2); border:0.5px solid var(--border); border-radius:12px; padding:12px 14px; text-align:center; cursor:pointer; transition:border-color 0.2s, background 0.2s, transform 0.15s; min-width:110px; flex:1; max-width:150px; z-index: 10; }
        .dgenie-pipeline-wrapper .agent-card:hover { border-color:var(--border-bright); background:#1a2440; transform:translateY(-2px); }
        .dgenie-pipeline-wrapper .agent-card .agent-icon { font-size:18px; margin-bottom:6px; }
        .dgenie-pipeline-wrapper .agent-card .agent-name { font-size:12px; font-weight:600; color:var(--text); line-height:1.3; }
        .dgenie-pipeline-wrapper .agent-card .agent-desc { font-size:10px; color:var(--text-muted); margin-top:4px; line-height:1.4; }
        
        .dgenie-pipeline-wrapper .accent-blue { border-color:rgba(79,142,255,0.25); }
        .dgenie-pipeline-wrapper .accent-green { border-color:rgba(61,214,140,0.2); }
        .dgenie-pipeline-wrapper .accent-yel { border-color:rgba(245,197,66,0.2); }
        .dgenie-pipeline-wrapper .accent-pink { border-color:rgba(255,107,107,0.2); }
        .dgenie-pipeline-wrapper .accent-purp { border-color:rgba(180,122,255,0.2); }
        
        .dgenie-pipeline-wrapper .ai-core { width:100px; height:100px; border-radius:50%; border:1.5px solid rgba(79,142,255,0.5); display:flex; flex-direction:column; align-items:center; justify-content:center; cursor:pointer; position:relative; background:var(--surface2); flex-shrink:0; transition:transform 0.2s; z-index: 10; }
        .dgenie-pipeline-wrapper .ai-core:hover { transform:scale(1.05); }
        .dgenie-pipeline-wrapper .ai-core::before { content:''; position:absolute; inset:-6px; border-radius:50%; border:0.5px solid rgba(79,142,255,0.2); animation:pulse-ring 2.5s ease-out infinite; }
        .dgenie-pipeline-wrapper .ai-core::after { content:''; position:absolute; inset:-14px; border-radius:50%; border:0.5px solid rgba(79,142,255,0.08); animation:pulse-ring 2.5s ease-out infinite 0.8s; }
        
        @keyframes pulse-ring { 0% { opacity:1; transform:scale(1); } 100%{ opacity:0; transform:scale(1.15); } }
        .dgenie-pipeline-wrapper .ai-core .ai-emoji { font-size:24px; }
        .dgenie-pipeline-wrapper .ai-core .ai-name { font-size:10px; font-weight:700; color:var(--accent); letter-spacing:1px; margin-top:4px; }
        
        .dgenie-pipeline-wrapper .capabilities { display:flex; gap:8px; margin-top:20px; padding-top:18px; border-top:0.5px solid var(--border); }
        .dgenie-pipeline-wrapper .cap-card { flex:1; background:rgba(10,14,26,0.6); border:0.5px solid var(--border); border-radius:10px; padding:10px 8px; text-align:center; cursor:pointer; transition:border-color 0.2s; }
        .dgenie-pipeline-wrapper .cap-card:hover { border-color:var(--border-bright); }
        .dgenie-pipeline-wrapper .cap-card .cap-icon { font-size:16px; margin-bottom:5px; }
        .dgenie-pipeline-wrapper .cap-card .cap-name { font-size:11px; font-weight:600; color:var(--text); line-height:1.3; }
        .dgenie-pipeline-wrapper .cap-card .cap-desc { font-size:10px; color:var(--text-muted); margin-top:2px; line-height:1.4; }
        
        .dgenie-pipeline-wrapper .status-bar { margin-top:16px; background:var(--surface); border:0.5px solid var(--border); border-radius:10px; padding:10px 16px; display:flex; align-items:center; gap:8px; font-size:11px; color:var(--text-muted); font-family:'JetBrains Mono',monospace; }
        .dgenie-pipeline-wrapper .status-dot { width:6px; height:6px; border-radius:50%; background:var(--accent3); box-shadow:0 0 6px var(--accent3); animation:blink 2s ease-in-out infinite; }
        @keyframes blink { 0%,100%{opacity:1} 50%{opacity:0.4} }
        .dgenie-pipeline-wrapper .status-text { color:var(--accent3); }

        .dgenie-pipeline-wrapper .output-item { display:flex; align-items:flex-start; gap:12px; padding:12px 14px; background:var(--surface); border:0.5px solid var(--border); border-radius:10px; margin-bottom:10px; cursor:pointer; transition:border-color 0.2s, background 0.2s; }
        .dgenie-pipeline-wrapper .output-item:hover, 
        .dgenie-pipeline-wrapper .output-item.active { border-color:var(--border-bright); background:var(--surface2); }
        .dgenie-pipeline-wrapper .output-dot { width:8px; height:8px; border-radius:50%; margin-top:4px; flex-shrink:0; }
        .dgenie-pipeline-wrapper .out-title { font-size:13px; font-weight:600; color:var(--text); }
        .dgenie-pipeline-wrapper .out-desc { font-size:11px; color:var(--text-muted); margin-top:3px; line-height:1.5; }

        .dgenie-pipeline-wrapper .tooltip { position:fixed; background:var(--surface2); border:0.5px solid var(--border-bright); border-radius:10px; padding:12px 16px; font-size:12px; color:var(--text); max-width:240px; pointer-events:none; opacity:0; transition:opacity 0.15s; z-index:999; line-height:1.6; }
        .dgenie-pipeline-wrapper .tooltip.show { opacity:1; }
        .dgenie-pipeline-wrapper .tooltip strong { color:var(--accent2); display:block; margin-bottom:4px; font-size:13px; }

        @keyframes highlight-flash { 0% { box-shadow:0 0 0 0 rgba(79,142,255,0.4); } 70% { box-shadow:0 0 0 8px rgba(79,142,255,0); } 100%{ box-shadow:0 0 0 0 rgba(79,142,255,0); } }
        .dgenie-pipeline-wrapper .flash { animation:highlight-flash 0.6s ease-out; }

        @keyframes dash-flow { from { stroke-dashoffset: 300; } to { stroke-dashoffset: 0; } }
        .dgenie-pipeline-wrapper .flow-path { fill: none; stroke-width: 1.5; stroke-dasharray: 6 5; opacity: 0.55; animation: dash-flow 3s linear infinite; }
        .dgenie-pipeline-wrapper .flow-path.fast { animation-duration: 2s; }
        .dgenie-pipeline-wrapper .flow-path.slow { animation-duration: 4.5s; }
        .dgenie-pipeline-wrapper .flow-path.mid { animation-duration: 3.5s; }
        .dgenie-pipeline-wrapper .glow-path { fill: none; stroke-width: 1; opacity: 0.12; }
      `}</style>

      <div className="dgenie-pipeline-wrapper">
        <div className="page">
          <header className="header">
            <h1>How <span>DataGenie</span> Works</h1>
            <p>AI-powered data analytics — upload any dataset and get instant SQL, charts &amp; insights</p>
          </header>

          <div className="layout-outer" id="layoutOuter" ref={layoutOuterRef}>
            <svg id="arrow-svg" ref={arrowSvgRef} aria-hidden="true" />

            <div className="layout" id="mainLayout">
              {/* LEFT COLUMN: SOURCE REPOSITORIES */}
              <aside className="left-col" id="leftCol">
                <div className="panel-title">Data Sources</div>

                <div className="source-group">
                  <div className="group-label">Enterprise Systems</div>
                  {LEFT_SOURCES.slice(0, 3).map((src) => (
                    <div
                      key={src.id}
                      id={src.id}
                      ref={(el) => (elementsRef.current[src.id] = el)}
                      data-tip={src.tip}
                      onMouseEnter={(e) => handleMouseEnter(e, src.tip)}
                      onMouseMove={handleMouseMove}
                      onMouseLeave={handleMouseLeave}
                      onClick={() => handleSourceClick(src.id, src.title)}
                      className="source-item"
                    >
                      <div className={`icon ${src.iconClass}`}>{src.icon}</div>
                      <div>
                        <div className="label">{src.title}</div>
                        <div className="sublabel">{src.sublabel}</div>
                      </div>
                      <div className={`dot ${src.id === 'src2' ? 'dot-blue' : ''}`} />
                    </div>
                  ))}
                </div>

                <div className="source-group">
                  <div className="group-label">File Uploads</div>
                  {LEFT_SOURCES.slice(3).map((src) => (
                    <div
                      key={src.id}
                      id={src.id}
                      ref={(el) => (elementsRef.current[src.id] = el)}
                      data-tip={src.tip}
                      onMouseEnter={(e) => handleMouseEnter(e, src.tip)}
                      onMouseMove={handleMouseMove}
                      onMouseLeave={handleMouseLeave}
                      onClick={() => handleSourceClick(src.id, src.title)}
                      className="source-item"
                    >
                      <div className={`icon ${src.iconClass}`}>{src.icon}</div>
                      <div>
                        <div className="label">{src.title}</div>
                        <div className="sublabel">{src.sublabel}</div>
                      </div>
                      <div className={`dot ${src.id === 'src3' || src.id === 'src4' ? 'dot-yellow' : src.id === 'src5' ? 'dot-blue' : ''}`} />
                    </div>
                  ))}
                </div>
              </aside>

              {/* CENTER COLUMN: INTEL ENGINE MATRIX */}
              <section className="center-col">
                <div className="panel-title" style={{ textAlign: 'center' }}>Intelligence Engine</div>
                <div className="engine-wrapper" id="engineBox" ref={engineBoxRef}>
                  <div className="engine-label">
                    <div className="engine-badge">DataGenie AI</div>
                    <div className="engine-subtitle">Analytics Intelligence Agent</div>
                  </div>
                  <div className="crew-label">Agent Crew</div>
                  
                  <div className="agents-top">
                    {AGENTS_TOP.map((agent, index) => (
                      <div
                        key={index}
                        ref={(el) => (elementsRef.current[`top-agent-${index}`] = el)}
                        data-tip={agent.tip}
                        onMouseEnter={(e) => handleMouseEnter(e, agent.tip)}
                        onMouseMove={handleMouseMove}
                        onMouseLeave={handleMouseLeave}
                        onClick={() => handleAgentClick(`top-agent-${index}`, agent.name)}
                        className={`agent-card ${agent.styleClass}`}
                      >
                        <div className="agent-icon">{agent.icon}</div>
                        <div className="agent-name" dangerouslySetInnerHTML={{ __html: agent.name.replace('\n', '<br/>') }} />
                        <div className="agent-desc">{agent.desc}</div>
                      </div>
                    ))}
                  </div>

                  <div className="ai-core-row">
                    <div
                      ref={(el) => (elementsRef.current['mid-agent-0'] = el)}
                      data-tip="Chart Agent|Picks the right chart type and builds an interactive Plotly figure."
                      onMouseEnter={(e) => handleMouseEnter(e, "Chart Agent|Picks the right chart type and builds an interactive Plotly figure.")}
                      onMouseMove={handleMouseMove}
                      onMouseLeave={handleMouseLeave}
                      onClick={() => handleAgentClick('mid-agent-0', 'Chart\nRenderer')}
                      className="agent-card accent-pink"
                    >
                      <div className="agent-icon">📈</div>
                      <div className="agent-name">Chart<br />Renderer</div>
                      <div className="agent-desc">Plotly auto-viz</div>
                    </div>

                    <div className="ai-core" onClick={handleCoreClick} id="aiCore" ref={aiCoreRef}>
                      <div className="ai-emoji">🤖</div>
                      <div className="ai-name">DATAGENIE</div>
                    </div>

                    <div
                      ref={(el) => (elementsRef.current['mid-agent-1'] = el)}
                      data-tip="Summary Agent|Reads SQL results and writes plain-English insight summaries."
                      onMouseEnter={(e) => handleMouseEnter(e, "Summary Agent|Reads SQL results and writes plain-English insight summaries.")}
                      onMouseMove={handleMouseMove}
                      onMouseLeave={handleMouseLeave}
                      onClick={() => handleAgentClick('mid-agent-1', 'Insight\nSummarizer')}
                      className="agent-card accent-purp"
                    >
                      <div className="agent-icon">📝</div>
                      <div className="agent-name">Insight<br />Summarizer</div>
                      <div className="agent-desc">Plain-English takeaways</div>
                    </div>
                  </div>

                  <div className="agents-bottom">
                    {AGENTS_BOTTOM.map((agent, index) => (
                      <div
                        key={index}
                        ref={(el) => (elementsRef.current[`bot-agent-${index}`] = el)}
                        data-tip={agent.tip}
                        onMouseEnter={(e) => handleMouseEnter(e, agent.tip)}
                        onMouseMove={handleMouseMove}
                        onMouseLeave={handleMouseLeave}
                        onClick={() => handleAgentClick(`bot-agent-${index}`, agent.name)}
                        className={`agent-card ${agent.styleClass}`}
                      >
                        <div className="agent-icon">{agent.icon}</div>
                        <div className="agent-name" dangerouslySetInnerHTML={{ __html: agent.name.replace('\n', '<br/>') }} />
                        <div className="agent-desc">{agent.desc}</div>
                      </div>
                    ))}
                  </div>

                  <div className="capabilities">
                    {CAPABILITIES.map((cap, index) => (
                      <div
                        key={index}
                        ref={(el) => (elementsRef.current[`cap-${index}`] = el)}
                        data-tip={cap.tip}
                        onMouseEnter={(e) => handleMouseEnter(e, cap.tip)}
                        onMouseMove={handleMouseMove}
                        onMouseLeave={handleMouseLeave}
                        onClick={() => handleAgentClick(`cap-${index}`, cap.name)}
                        className="cap-card"
                      >
                        <div className="cap-icon">{cap.icon}</div>
                        <div className="cap-name" dangerouslySetInnerHTML={{ __html: cap.name.replace('\n', '<br/>') }} />
                        <div className="cap-desc">{cap.desc}</div>
                      </div>
                    ))}
                  </div>

                  <div className="status-bar">
                    <div className="status-dot" />
                    <span className="status-text" id="statusText">{statusText}</span>
                  </div>
                </div>
              </section>

              {/* RIGHT COLUMN: OUTBOUND PRESENTATION SHAPES */}
              <aside className="right-col" id="rightCol">
                <div className="panel-title" style={{ textAlign: 'right' }}>Analytics Outputs</div>
                {OUTPUT_CARDS.map((card) => (
                  <div
                    key={card.id}
                    id={card.id}
                    ref={(el) => (elementsRef.current[card.id] = el)}
                    onClick={() => flashElement(card.id)}
                    className="output-item"
                  >
                    <div className="output-dot" style={{ background: card.color, boxShadow: `0 0 6px ${card.color}` }} />
                    <div>
                      <div className="out-title">{card.title}</div>
                      <div className="out-desc">{card.desc}</div>
                    </div>
                  </div>
                ))}
              </aside>
            </div>
          </div>
        </div>

        {/* METRICS CANVAS TOOLTIP CONTAINER */}
        <div className={`tooltip ${tooltip.show ? 'show' : ''}`} id="tooltip" style={{ left: `${tooltip.x}px`, top: `${tooltip.y}px` }}>
          <strong>{tooltip.title}</strong>
          {tooltip.desc}
        </div>
      </div>
    </>
  );
}